### ISSUE TITLE
Option to disable self-updating?

### ISSUE THREAD

**Issue by davisshaver** [scripting/nodeStorage#6]
Looking to move my 1999 instance and so I'm trying to run this inside pagePark. Looks like when the update runs, nodestorage overwrites parent app `package.json` since the versions don't match. I think this could be solved by updating the paths to all be based on the main `nodestorage` file rather than the process cwd, or we could add an option to disable self updating too. What do you think?

**Comment by scripting** [comment]
To answer the question in the title of your issue, there is a way to disable self-updating of nodeStorage. It's explained here -- 

https://github.com/scripting/1999-project/blob/master/docs/updating.md

The docs for using nodeStorage are in the 1999-project repo. They shouldn't be there, but that's where they are. 

Hope this helps.

**Comment by davisshaver** [comment]
Whoops, should have checked there. Thanks @scripting!

**Comment by scripting** [comment]
BTW, I added a link to the docs on the 1999-project site from the nodeStorage readme. 

https://github.com/scripting/nodeStorage#links

Dave
